### ISSUE TITLE
[feat] TargetCalView와 firestore 연결 관련

### ISSUE THREAD

**Issue by oceanooooo** [MyMomii/MyMomii-target#11]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟡 Todo

- [x] TargetCalView 내비게이션 백버튼 히든
- [x] TargetCalView 설정 버튼 추가
- [x] DateFormatter(yyyyMMdd) 적용
- [x] eventsArrayDone에 샘플 데이터 추가 ["20231101", "20231102", "20231103"]
- [x] firestore 저장된 증상 string에 맞는 이미지 출력

**Comment by oceanooooo** [comment]
PR #13
branch
- feat/#11-TargetCalView-Observable
- feat/#11-TargetCalView+Firestore
